#ifndef _CNN_TB_H_
#define _CNN_TB_H_

#include <inttypes.h>
#include "stdlib.h"

#define NUMBER_OF_INPUTS 5
#define SIZE 256
#define L1_INPUT_HEIGHT SIZE
#define L1_INPUT_WIDTH SIZE
#define L2_INPUT_HEIGHT ((L1_INPUT_HEIGHT - 2) / 2)
#define L3_INPUT_HEIGHT ((L2_INPUT_HEIGHT - 2) / 2)
#define L2_INPUT_WIDTH (L1_INPUT_WIDTH / 2)
#define L3_INPUT_WIDTH (L2_INPUT_WIDTH / 2)
#define ROWS_PER_ITERATION 2
#define INPUT_VALUES_PER_ITERATION (ROWS_PER_ITERATION * IN_CHANNELS * L1_INPUT_WIDTH)
#define WEIGHT_ROWS_PER_ITERATION 256
#define WEIGHTS_PER_ROW 16
#define NUMBER_OF_CNN_CALLS (L1_INPUT_WIDTH * 2)
#define TOTAL_OUTPUT_SIZE (L2_KERNELS * OUTPUT_HEIGHT * OUTPUT_WIDTH)
#define L3_OUTPUT_SIZE 16

#endif 
